title: Crossroad Pattern Finder
description: Find nether fortress crossroad patterns easily with this tool.
author: Mews
email: ar754456@gmail.com

url: "https://mews.github.io"
baseurl: "/crossroad-finder"

logo: /assets/images/seo/logo.png

image: 
  path: /assets/images/seo/banner.png

google_site_verification: C3QKOpfcH1sx3mwpP5H-XphVxZUaXJ9nLrvwkFjNrs4

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
